language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# 실행 권한 부여
before_install:
  chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r murmul-er * # 전체 압축
  - mkdir -p deploy # zip파일을 담을 디렉토리 생성
  - mv murmul-er.zip deploy/murmul-er.zip # zip파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: murmul-er-deploy # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      repo: YJeongKim/Murmul-er_two
      branch: master

  - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
      secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
      bucket: murmul-er-deploy # S3 버킷
      key: murmul-er.zip # 빌드 파일을 압축해서 전달
      bundle_type: zip
      application: murmul-er # CodeDeploy 어플리케이션
      deployment_group: murmul-er-group # CodeDeploy 배포 그룹
      region: ap-northeast-2
      wait-until-deployed: true
      on:
        repo: YJeongKim/Murmul-er_two
        branch: master

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - yjeongisme@gmail.com
